<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/roles.proto

namespace Services\Roles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.roles.RequestCode</code>
 */
class RequestCode extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string role_code = 1;</code>
     */
    protected $role_code = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $role_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Roles::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string role_code = 1;</code>
     * @return string
     */
    public function getRoleCode()
    {
        return $this->role_code;
    }

    /**
     * Generated from protobuf field <code>string role_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRoleCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->role_code = $var;

        return $this;
    }

}

