<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/users.proto

namespace Services\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.users.RawData</code>
 */
class RawData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string users_id = 1;</code>
     */
    protected $users_id = '';
    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string inserted_at = 2;</code>
     */
    protected $inserted_at = '';
    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string updated_at = 3;</code>
     */
    protected $updated_at = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $users_id
     *     @type string $inserted_at
     *           Using string to store the timestamp in ISO format
     *     @type string $updated_at
     *           Using string to store the timestamp in ISO format
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proto\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string users_id = 1;</code>
     * @return string
     */
    public function getUsersId()
    {
        return $this->users_id;
    }

    /**
     * Generated from protobuf field <code>string users_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUsersId($var)
    {
        GPBUtil::checkString($var, True);
        $this->users_id = $var;

        return $this;
    }

    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string inserted_at = 2;</code>
     * @return string
     */
    public function getInsertedAt()
    {
        return $this->inserted_at;
    }

    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string inserted_at = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInsertedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->inserted_at = $var;

        return $this;
    }

    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string updated_at = 3;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string updated_at = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

}

