<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/users.proto

namespace Services\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.users.resdata</code>
 */
class resdata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .services.users.RESUSERS data = 1;</code>
     */
    private $data;
    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     */
    protected $total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Services\Users\RESUSERS>|\Google\Protobuf\Internal\RepeatedField $data
     *     @type int $total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proto\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .services.users.RESUSERS data = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .services.users.RESUSERS data = 1;</code>
     * @param array<\Services\Users\RESUSERS>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Services\Users\RESUSERS::class);
        $this->data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>int32 total = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

}

