<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/roles.proto

namespace Services\Roles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.roles.ResRoles</code>
 */
class ResRoles extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string roles_code = 2;</code>
     */
    protected $roles_code = '';
    /**
     * Generated from protobuf field <code>string roles_desc = 3;</code>
     */
    protected $roles_desc = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $roles_code
     *     @type string $roles_desc
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proto\Roles::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string roles_code = 2;</code>
     * @return string
     */
    public function getRolesCode()
    {
        return $this->roles_code;
    }

    /**
     * Generated from protobuf field <code>string roles_code = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRolesCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->roles_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string roles_desc = 3;</code>
     * @return string
     */
    public function getRolesDesc()
    {
        return $this->roles_desc;
    }

    /**
     * Generated from protobuf field <code>string roles_desc = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRolesDesc($var)
    {
        GPBUtil::checkString($var, True);
        $this->roles_desc = $var;

        return $this;
    }

}

