<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/roles.proto

namespace GPBMetadata\Proto;

class Roles
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xAC\x02\x0A\x11proto/roles.proto\x12\x0Eservices.roles\" \x0A\x0BRequestCode\x12\x11\x0A\x09role_code\x18\x01 \x01(\x09\">\x0A\x08ResRoles\x12\x0A\x0A\x02id\x18\x01 \x01(\x05\x12\x12\x0A\x0Aroles_code\x18\x02 \x01(\x09\x12\x12\x0A\x0Aroles_desc\x18\x03 \x01(\x09\"@\x0A\x07ResData\x12&\x0A\x04data\x18\x01 \x03(\x0B2\x18.services.roles.ResRoles\x12\x0D\x0A\x05total\x18\x02 \x01(\x052[\x0A\x0DRolesServices\x12J\x0A\x0FFindByRolesCode\x12\x1B.services.roles.RequestCode\x1A\x18.services.roles.ResRoles\"\x00b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

