<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/users.proto

namespace Services\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.users.GeneratedMap</code>
 */
class GeneratedMap extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string insertedAt = 2;</code>
     */
    protected $insertedAt = '';
    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string updatedAt = 3;</code>
     */
    protected $updatedAt = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $insertedAt
     *           Using string to store the timestamp in ISO format
     *     @type string $updatedAt
     *           Using string to store the timestamp in ISO format
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string insertedAt = 2;</code>
     * @return string
     */
    public function getInsertedAt()
    {
        return $this->insertedAt;
    }

    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string insertedAt = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInsertedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->insertedAt = $var;

        return $this;
    }

    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string updatedAt = 3;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Using string to store the timestamp in ISO format
     *
     * Generated from protobuf field <code>string updatedAt = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updatedAt = $var;

        return $this;
    }

}

