<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/users.proto

namespace Services\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.users.InsertResult</code>
 */
class InsertResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .services.users.Identifier identifiers = 1;</code>
     */
    private $identifiers;
    /**
     * Generated from protobuf field <code>repeated .services.users.GeneratedMap generatedMaps = 2;</code>
     */
    private $generatedMaps;
    /**
     * Generated from protobuf field <code>repeated .services.users.RawData raw = 3;</code>
     */
    private $raw;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Services\Users\Identifier>|\Google\Protobuf\Internal\RepeatedField $identifiers
     *     @type array<\Services\Users\GeneratedMap>|\Google\Protobuf\Internal\RepeatedField $generatedMaps
     *     @type array<\Services\Users\RawData>|\Google\Protobuf\Internal\RepeatedField $raw
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .services.users.Identifier identifiers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIdentifiers()
    {
        return $this->identifiers;
    }

    /**
     * Generated from protobuf field <code>repeated .services.users.Identifier identifiers = 1;</code>
     * @param array<\Services\Users\Identifier>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIdentifiers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Services\Users\Identifier::class);
        $this->identifiers = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .services.users.GeneratedMap generatedMaps = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGeneratedMaps()
    {
        return $this->generatedMaps;
    }

    /**
     * Generated from protobuf field <code>repeated .services.users.GeneratedMap generatedMaps = 2;</code>
     * @param array<\Services\Users\GeneratedMap>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGeneratedMaps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Services\Users\GeneratedMap::class);
        $this->generatedMaps = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .services.users.RawData raw = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRaw()
    {
        return $this->raw;
    }

    /**
     * Generated from protobuf field <code>repeated .services.users.RawData raw = 3;</code>
     * @param array<\Services\Users\RawData>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRaw($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Services\Users\RawData::class);
        $this->raw = $arr;

        return $this;
    }

}

