<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/users.proto

namespace Services\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>services.users.RESUSERS</code>
 */
class RESUSERS extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string username = 2;</code>
     */
    protected $username = '';
    /**
     * Generated from protobuf field <code>string password = 3;</code>
     */
    protected $password = '';
    /**
     * Generated from protobuf field <code>string is_login = 4;</code>
     */
    protected $is_login = '';
    /**
     * Generated from protobuf field <code>string roles_id = 5;</code>
     */
    protected $roles_id = '';
    /**
     * Generated from protobuf field <code>string status = 6;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string last_login = 7;</code>
     */
    protected $last_login = '';
    /**
     * Generated from protobuf field <code>string employee_id = 8;</code>
     */
    protected $employee_id = '';
    /**
     * Generated from protobuf field <code>string students_id = 9;</code>
     */
    protected $students_id = '';
    /**
     * Generated from protobuf field <code>string created_at = 10;</code>
     */
    protected $created_at = '';
    /**
     * Generated from protobuf field <code>string updated_at = 11;</code>
     */
    protected $updated_at = '';
    /**
     * Generated from protobuf field <code>.services.users.RolesUsers roles = 12;</code>
     */
    protected $roles = null;
    /**
     * Generated from protobuf field <code>.services.users.SuperAdminUsers profile = 13;</code>
     */
    protected $profile = null;
    /**
     * Generated from protobuf field <code>.services.users.TeacherStudentUsers profile_teacher = 14;</code>
     */
    protected $profile_teacher = null;
    /**
     * Generated from protobuf field <code>.services.users.TeacherStudentUsers profile_student = 15;</code>
     */
    protected $profile_student = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $id
     *     @type string $username
     *     @type string $password
     *     @type string $is_login
     *     @type string $roles_id
     *     @type string $status
     *     @type string $last_login
     *     @type string $employee_id
     *     @type string $students_id
     *     @type string $created_at
     *     @type string $updated_at
     *     @type \Services\Users\RolesUsers $roles
     *     @type \Services\Users\SuperAdminUsers $profile
     *     @type \Services\Users\TeacherStudentUsers $profile_teacher
     *     @type \Services\Users\TeacherStudentUsers $profile_student
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Users::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Generated from protobuf field <code>string username = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Generated from protobuf field <code>string password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->password = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string is_login = 4;</code>
     * @return string
     */
    public function getIsLogin()
    {
        return $this->is_login;
    }

    /**
     * Generated from protobuf field <code>string is_login = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIsLogin($var)
    {
        GPBUtil::checkString($var, True);
        $this->is_login = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string roles_id = 5;</code>
     * @return string
     */
    public function getRolesId()
    {
        return $this->roles_id;
    }

    /**
     * Generated from protobuf field <code>string roles_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRolesId($var)
    {
        GPBUtil::checkString($var, True);
        $this->roles_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 6;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_login = 7;</code>
     * @return string
     */
    public function getLastLogin()
    {
        return $this->last_login;
    }

    /**
     * Generated from protobuf field <code>string last_login = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setLastLogin($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_login = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string employee_id = 8;</code>
     * @return string
     */
    public function getEmployeeId()
    {
        return $this->employee_id;
    }

    /**
     * Generated from protobuf field <code>string employee_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setEmployeeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->employee_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string students_id = 9;</code>
     * @return string
     */
    public function getStudentsId()
    {
        return $this->students_id;
    }

    /**
     * Generated from protobuf field <code>string students_id = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setStudentsId($var)
    {
        GPBUtil::checkString($var, True);
        $this->students_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string created_at = 10;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>string created_at = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 11;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>string updated_at = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.services.users.RolesUsers roles = 12;</code>
     * @return \Services\Users\RolesUsers|null
     */
    public function getRoles()
    {
        return $this->roles;
    }

    public function hasRoles()
    {
        return isset($this->roles);
    }

    public function clearRoles()
    {
        unset($this->roles);
    }

    /**
     * Generated from protobuf field <code>.services.users.RolesUsers roles = 12;</code>
     * @param \Services\Users\RolesUsers $var
     * @return $this
     */
    public function setRoles($var)
    {
        GPBUtil::checkMessage($var, \Services\Users\RolesUsers::class);
        $this->roles = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.services.users.SuperAdminUsers profile = 13;</code>
     * @return \Services\Users\SuperAdminUsers|null
     */
    public function getProfile()
    {
        return $this->profile;
    }

    public function hasProfile()
    {
        return isset($this->profile);
    }

    public function clearProfile()
    {
        unset($this->profile);
    }

    /**
     * Generated from protobuf field <code>.services.users.SuperAdminUsers profile = 13;</code>
     * @param \Services\Users\SuperAdminUsers $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Services\Users\SuperAdminUsers::class);
        $this->profile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.services.users.TeacherStudentUsers profile_teacher = 14;</code>
     * @return \Services\Users\TeacherStudentUsers|null
     */
    public function getProfileTeacher()
    {
        return $this->profile_teacher;
    }

    public function hasProfileTeacher()
    {
        return isset($this->profile_teacher);
    }

    public function clearProfileTeacher()
    {
        unset($this->profile_teacher);
    }

    /**
     * Generated from protobuf field <code>.services.users.TeacherStudentUsers profile_teacher = 14;</code>
     * @param \Services\Users\TeacherStudentUsers $var
     * @return $this
     */
    public function setProfileTeacher($var)
    {
        GPBUtil::checkMessage($var, \Services\Users\TeacherStudentUsers::class);
        $this->profile_teacher = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.services.users.TeacherStudentUsers profile_student = 15;</code>
     * @return \Services\Users\TeacherStudentUsers|null
     */
    public function getProfileStudent()
    {
        return $this->profile_student;
    }

    public function hasProfileStudent()
    {
        return isset($this->profile_student);
    }

    public function clearProfileStudent()
    {
        unset($this->profile_student);
    }

    /**
     * Generated from protobuf field <code>.services.users.TeacherStudentUsers profile_student = 15;</code>
     * @param \Services\Users\TeacherStudentUsers $var
     * @return $this
     */
    public function setProfileStudent($var)
    {
        GPBUtil::checkMessage($var, \Services\Users\TeacherStudentUsers::class);
        $this->profile_student = $var;

        return $this;
    }

}

